---

- hosts: nodes
  roles:
    - { role: elasticsearch, es_instance_name: "node1", es_heap_size: "1g", es_config: {network.host: "_eth0_", discovery.zen.ping.unicast.hosts: "ansible-test:9300", http.port: 9200, transport.tcp.port: 9300, node.data: false, node.master: true, bootstrap.mlockall: true } }
    - { role: elasticsearch, es_instance_name: "node2", es_heap_size: "1g", es_config: {network.host: "_eth0_", discovery.zen.ping.unicast.hosts: "ansible-test:9300", http.port: 9201, transport.tcp.port: 9301, node.data: true, node.master: true, bootstrap.mlockall: true } }
  vars:
    es_cluster_name: test-cluster
